### ISSUE TITLE
Debian 8下无显示

### ISSUE THREAD

**Issue by maidmeow4** [hustcc/simple-shields#4]
环境：Debian 8 + Apache 2.4.23 + PHP 5.6.26。mod_rewrite已开启

用git将源码clone下来后放在`/var/www/html/static/tag`下

HTTP响应200但是什么也没显示

是需要再给Apache或PHP安装什么模块吗？

**Comment by hustcc** [comment]
PHP 需要有 gd 模块。

或者你看看有什么报错的。

**Comment by maidmeow4** [comment]
@hustcc 
感谢回复！PHP 的 gd 模块确实已经安装了。（`php5 -m` 显示有 gd）
直接在 console 下执行 `php5 /var/www/html/static/tag/api.php` 有两个 warning
`PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/html/static/tag/api.php on line 5
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/html/static/tag/api.php on line 5`

**Comment by hustcc** [comment]
`verdana.ttf` 这个字体文件是找得到的吗？

你可以 `cd /var/www/html/static/tag/`

然后 `php5 api.php`.

**Comment by maidmeow4** [comment]
还是会有 warning
`root@M4-Pi:/var/www/html/static/tag# php5 api.php
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/html/static/tag/api.php on line 5
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/html/static/tag/api.php on line 5`

**Comment by hustcc** [comment]
在尝试一下修改 api.php 第五行

``` php
$bbox = imagettfbbox(11.0, 0, 'verdana.ttf', $text);
```

改成绝对路径：

``` php
$bbox = imagettfbbox(11.0, 0, '/var/www/html/static/tag/verdana.ttf', $text);
```

google了一下好像存在这个相对路径或者绝对路径的问题，你试试看。

**Comment by maidmeow4** [comment]
感谢，这样改后确实解决了问题。

**Comment by hustcc** [comment]
找到最终解决办法了：[http://stackoverflow.com/questions/3809893/could-not-find-open-font-when-using-php-gd](http://stackoverflow.com/questions/3809893/could-not-find-open-font-when-using-php-gd)

非常感谢你的反馈。一会我提交一下.

**Comment by hustcc** [comment]
已经设置了 `GDFONTPATH`，希望能够在你那边的环境帮我测试一下这样是否可行，感谢~^_^

拉取最新代码即可。

**Comment by maidmeow4** [comment]
重新 clone 了一下，工作正常！
