### ISSUE TITLE
504 gateway timeout

### ISSUE THREAD

**Issue by duoduoeeee** [hustcc/simple-shields#5]
环境：windows10 x64 WNMP 集成包，3.1.0.0，nginx

问题：没开 URL 重写，将php项目文件复制进 webroot 之后，打开如下地址

<http://localhost/api.php?subject=s&status=s&color=brightgreen>

然后浏览器一直转圈，最后报了个 504 timeout。

wnmp 里提供了一个 php_gd2.dll，也按要求打开了

字体文件也在 webroot 里，并没有丢

发生了什么

**Comment by duoduoeeee** [comment]
放我服务器上……又好了……很迷……issue 关闭中

**Comment by hustcc** [comment]
😁
